env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules: {
  no-return-await: 0,
  no-console: 0,
  prefer-destructuring: 0,
  arrow-body-style: 0,
}
